### ISSUE TITLE
You are unable to broadcast unless you update to the latest version of Instagram.

### ISSUE THREAD

**Issue by krishnPratapSingh** [kingbotss/instagram-private-api#2]
POST /api/v1/live/create/ - 400 Bad Request; You are unable to broadcast unless you update to the latest version of Instagram.

can you please help, I have seen your reply on my thread on dilame/instagram-private-api but admin has deleted my bug report.

Help me if you have any solution to this

**Comment by Alisarlak71** [comment]
Hello how i can fix this ? i update to [1.45.3] but still i get this error !

**Comment by kingbotss** [comment]
You have to pass latest user agent in headers. I think it fixes your issue.
